package com.managemetn.schoolmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LibraryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryAllPropertiesEquals(Library expected, Library actual) {
        assertLibraryAutoGeneratedPropertiesEquals(expected, actual);
        assertLibraryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryAllUpdatablePropertiesEquals(Library expected, Library actual) {
        assertLibraryUpdatableFieldsEquals(expected, actual);
        assertLibraryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryAutoGeneratedPropertiesEquals(Library expected, Library actual) {
        assertThat(expected)
            .as("Verify Library auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryUpdatableFieldsEquals(Library expected, Library actual) {
        assertThat(expected)
            .as("Verify Library relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getBlock()).as("check block").isEqualTo(actual.getBlock()))
            .satisfies(e -> assertThat(e.getIsVisible()).as("check isVisible").isEqualTo(actual.getIsVisible()))
            .satisfies(e -> assertThat(e.getIsDeleted()).as("check isDeleted").isEqualTo(actual.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryUpdatableRelationshipsEquals(Library expected, Library actual) {
        // empty method
    }
}
